### ISSUE TITLE
Consider renaming to something less generic

### ISSUE THREAD

**Issue by unixorn** [mh-firouzjaah/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by mh-firouzjah** [comment]
hi, could you please give me an example of a good name which you mean?
I have no concern to change the name, it was just something. it will be renamed
